// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgzvczeybydzatvblpvz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJnenZjemV5YnlkemF0dmJscHZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MzU2MDIsImV4cCI6MjA2MDQxMTYwMn0.M-rQDwBwdn3z0BbFE5C1ZdtuxP9KzD1FOM5jQrkAfB0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);