
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txokkuqusyhfsybezmrm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4b2trdXF1c3loZnN5YmV6bXJtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyODcyNDksImV4cCI6MjA2MDg2MzI0OX0.y4mnaN0u-W-FfAqvezlkCUKGVLO6KCu9BlcgnWjjqhg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storageKey: 'leju-auth-token',
  }
});
